title: "Prof Carlos Correia"
author: "Carlos Correia"
description: "Materiais de aula para meus alunos do SENAI Pato Branco/PR."
url: "https://profcarlos-senai.github.io"
baseurl: ""

theme: minima

minima.skin: dark
minima.nav_pages: [home, about]