title: "Prof Carlos Correia"
author: "Carlos Correia"
description: "Materiais de aula para meus alunos do SENAI Pato Branco/PR."
url: "https://profcarlos-senai.github.io"
baseurl: ""

theme: minima

minima:
  skin: classic 
  header_pages:
    - about.md
    - contact.md
  nav_pages:
    - about.md
    - contact.md